/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lulli
 */
public class trainerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form trainerDashboard
     */
    public trainerDashboard() {
        getTrainerID();
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTrainer.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnTrainer.setForeground(new java.awt.Color(204, 204, 204));
        btnTrainer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrainer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrainer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrainerMouseClicked(evt);
            }
        });
        getContentPane().add(btnTrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 190, 40));

        btnRequest.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        btnRequest.setForeground(new java.awt.Color(204, 204, 204));
        btnRequest.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRequest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRequestMouseClicked(evt);
            }
        });
        getContentPane().add(btnRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 190, 30));

        btnPayment.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        btnPayment.setForeground(new java.awt.Color(204, 204, 204));
        btnPayment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPaymentMouseClicked(evt);
            }
        });
        getContentPane().add(btnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 190, 40));

        btnAssigned.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        btnAssigned.setForeground(new java.awt.Color(204, 204, 204));
        btnAssigned.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAssigned.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAssigned.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAssignedMouseClicked(evt);
            }
        });
        getContentPane().add(btnAssigned, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 190, 40));

        lblTrainerID.setBackground(new java.awt.Color(204, 204, 204));
        lblTrainerID.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTrainerID.setForeground(new java.awt.Color(204, 204, 204));
        lblTrainerID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblTrainerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 100, 100));

        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 70, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trainer dashboard.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrainerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrainerMouseClicked
        
    }//GEN-LAST:event_btnTrainerMouseClicked

    private void btnRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRequestMouseClicked
        new pending().setVisible(true);
    }//GEN-LAST:event_btnRequestMouseClicked

    private void btnPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentMouseClicked
        new salaryTrainer().setVisible(true);
    }//GEN-LAST:event_btnPaymentMouseClicked

    private void btnAssignedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssignedMouseClicked
        new clients().setVisible(true);
    }//GEN-LAST:event_btnAssignedMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to Logout", "Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void getTrainerID() {
        String name = btnTrainer.getText();
        System.out.println("Name input: " + name); // Debug statement
        Connection dbconn = DBConnection.connectDB();
            try {
                PreparedStatement st = dbconn.prepareStatement("SELECT id FROM trainers WHERE name = ?");
                st.setString(1, name);
                ResultSet res = st.executeQuery();
                if (res.next()) {
                    int trainerId = res.getInt("id");
                    // Display the user ID in another label or perform any other desired action
                    lblTrainerID.setText(String.valueOf(trainerId));
                }
                st.close();
                dbconn.close();
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trainerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trainerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trainerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trainerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trainerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JLabel btnAssigned = new javax.swing.JLabel();
    private javax.swing.JLabel btnLogout;
    public static final javax.swing.JLabel btnPayment = new javax.swing.JLabel();
    public static final javax.swing.JLabel btnRequest = new javax.swing.JLabel();
    public static final javax.swing.JLabel btnTrainer = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel2;
    public static final javax.swing.JLabel lblTrainerID = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
